### ISSUE TITLE
Consolidate error checking

### ISSUE THREAD

**Issue by canweriotnow** [canweriotnow/exercism-emacs#1]
I moved the exercism command definition to a single `defvar` as follows:

``` elisp
(defvar *exercism-cmd*
  (replace-regexp-in-string "\n$" ""
                            (shell-command-to-string "which exercism")))
```

But I'm still checking for non-sero length in each place it's called, e.g.:

``` elisp
;;;###autoload
(defun exercism-submit ()
  (interactive)
  (let ((exercise buffer-file-name)
        (cmd *exercism-cmd*))
      (if (zerop (length cmd))
          (user-error "exercism not found")
        (message "Result: %s" (shell-command-to-string (concat cmd " submit " exercise))))))
```

The error checking (for the existence of the exercism cli) should either happen on load or be moved to a separate fun. Once that happens, it would be nice to prompt the user to install exercism or configure the path in a `defcustom` or whatever.

Eventual goal is to replicate all CLI functionality, but I think wrapping it is the way to go for now.

**Comment by verdammelt** [comment]
Reviewing the code it looks to me that it could be made more concise by extracting function that runs an exercism command. This would like you get rid of the boilerplate of binding `cmd` in a let in each function, removing the error handling when `cmd` is zero length (by moving it into the extracted function) and then the final line would look something like `(message "Result: %s" (execute-command "submit" exercise))`

If that sounds good I'll gladly do that refactoring and send a pull request.

**Comment by canweriotnow** [comment]
That sounds great, thanks!

**Comment by canweriotnow** [comment]
@verdammelt take a look at the change, tell me what you think... it seems to do the job properly. The only thing I didn't get to test much was submitting, but the optional arg for the exercise name seems to work properly.

**Comment by verdammelt** [comment]
I had a little bit more change in mind (just a little) - pull request #10
