### ISSUE TITLE
Mock .exercism.json data for CI testing

### ISSUE THREAD

**Issue by canweriotnow** [canweriotnow/exercism-emacs#9]
Related to #8

**Comment by canweriotnow** [comment]
I tried adding `fixtures/exercism.json` under the test dir and using `custom-set-variables` to point to the dummy config, but no luck. CI builds are still erroring on not inding `~/.exercism.json`.

Any ideas @wobh or @verdammelt?

**Comment by canweriotnow** [comment]
Okay, it was simple enough, just at this line to `before_install` in `.travis.yml`:

`- cp test/fixtures/exercism.json ~/.exercism.json`

The build is green! Of course, the tests don't actually test anything yet, but the CI config is coming along :smile:

**Comment by verdammelt** [comment]
"The build is green! Of course, the tests don't actually test anything yet..." don't spoil the moment with reality.

**Comment by canweriotnow** [comment]
@verdammelt Last commit, I added a trivial test that actually checks a function in the package, and it's still green! Wooooo!!!

**Comment by verdammelt** [comment]
wooo!!!!
